version: '3.9'

services:
  postgres:
    image: docker.io/bitnami/postgresql:14.4.0
    environment:
      POSTGRESQL_PASSWORD: db-password-change-me
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 2s
      timeout: 1s
      retries: 6

  hasura-engine:
    build:
      context: ./hasura
      dockerfile: engine.Dockerfile
    ports:
      - '8080:8080'
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:db-password-change-me@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret-change-me
      HASURA_GRAPHQL_LOG_LEVEL: warn
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'curl --fail http://localhost:8080/healthz || exit 1'
      interval: 5s
      timeout: 2s
      retries: 6

  hasura-console:
    build:
      context: ./hasura
      dockerfile: console.Dockerfile
    init: true
    ports:
      - '9693:9693'
      - '9695:9695'
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret-change-me
    volumes:
      - ./hasura:/usr/src/hasura
    depends_on:
      hasura-engine:
        condition: service_healthy

  app:
    image: node:18.10.0-alpine3.16
    command: sh -c "yarn install && yarn start"
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 9991:9991
      - 3000:3000
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: admin-secret-change-me
    depends_on:
      hasura-engine:
        condition: service_healthy
