// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	ID        string                 `json:"id"`
	Name      string                 `json:"name"`
	Geography map[string]interface{} `json:"geography"`
}
