version: '3'
services:
  database:
    image: 'postgres:14'
    ports:
      - '54322:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
