name: 'Setup Node'
description: 'This action install node and cache modules. It uses pnpm as package manager.'
inputs:
  node-version:
    description: 'The node version to install (Default: lts)'
    default: 'lts/*'
    required: false
  working-directory:
    description: 'The working directory of your node package'
    default: '.'
    required: false
  repo-token:
    description: 'The github secret'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Protoc
      uses: abelfodil/protoc-action@v1
      with:
        protoc-version: '21.5'

    - uses: pnpm/action-setup@v2.2.2
      id: pnpm-install
      with:
        version: 7.9.0
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: setup pnpm config registry
      run: pnpm config set registry https://registry.npmjs.org
      shell: bash
