name: Issue Report
description: Report a WunderGraph issue
title: '[Issue]: '
labels: ['triage', 'issue']
assignees:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the WunderGraph community.
        Thank you for reporting an issue with our software.

        ## Issue Description
        Please give us a brief description of the issue you're experiencing.
        This will help us identify the scope and priority of this issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: When using WunderGraph I found that ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Reproduction path
        The first step of us working on addressing this issue is that we validate the issue by reproducing it.
        It's important that we can reproduce the issue on an environment that is not your computer or server environment.

        Please include relevant information such as:

        * Versions of the software you rely on:
          * WunderGraph
          * NodeJS, PNPM
          * APIs and databases ...
        * Relevant snippets from:
          * `.wundergraph/wundergraph.server.ts`
          * `.wundergraph/wundergraph.config.ts`
          * `.wundergraph/operations/*.graphql`

        **Be careful not to share any passwords or private connection strings.**

        The more details you provide here, the easier it will be for us to reproduce, identify and solve the issue.
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      placeholder: This is how I can reproduce this issue ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Next steps

        WunderGraph is an Open Source project. That means that the priority we assign to this issue might not align with your business needs.
        If you need this issue to be expedited, understand that we are open to the following options:

          * Consider writing a Test Case for this issue and submitting a Pull Request for it.
          * If you have the ability to do so, consider looking into the issue yourself and open a Pull Request for this.
          * If you haven't already, talk to [Sales](https://wundergraph.com/contact/sales) to discuss further options, which includes paid support.
