package codegeneration

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

const (
	serverEntryPointFilename = "server.ts"
)

var (
	wunderGraphServerTemplate = template.Must(template.New(serverEntryPointFilename).Parse(`
// Code generated by wunderctl. DO NOT EDIT.

import { startWunderGraphServer } from "@wundergraph/sdk/server";
import config from '../../wundergraph.config';
{{ if .HasWunderGraphServerTs }}import serverConfig from '../../wundergraph.server';{{ end }}

startWunderGraphServer(config{{ if .HasWunderGraphServerTs }}, serverConfig{{ end }});`))
)

type wunderGraphServerTemplateData struct {
	HasWunderGraphServerTs bool
}

func generateWunderGraphServerTS(wunderGraphDir string) (string, error) {
	st, err := os.Stat(filepath.Join(wunderGraphDir, "wundergraph.server.ts"))
	if err != nil && !os.IsNotExist(err) {
		return "", err
	}
	data := &wunderGraphServerTemplateData{
		HasWunderGraphServerTs: err == nil && !st.IsDir(),
	}
	generated := filepath.Join(wunderGraphDir, generatedDirectory, "server")
	var buf bytes.Buffer
	if err := wunderGraphServerTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	if err := os.MkdirAll(generated, os.ModePerm); err != nil {
		return "", fmt.Errorf("error creating %s: %s", generated, err)
	}
	entryPointFilename := filepath.Join(generated, serverEntryPointFilename)
	if err := os.WriteFile(entryPointFilename, buf.Bytes(), 0644); err != nil {
		return "", fmt.Errorf("error creating %s: %s", entryPointFilename, err)
	}
	return entryPointFilename, nil
}

func ServerEntryPoint(wunderGraphDir string) (string, error) {
	return generateWunderGraphServerTS(wunderGraphDir)
}
