// Code generated by wunderctl. DO NOT EDIT.

export interface CountdownInput {
	from: number;
}

export interface HelloInput {
	hello: string;
}

export interface ProtectedWeatherInput {
	forCity: string;
}

export interface SetNameInput {
	name: string;
}

export interface TestInput {
	input: ('EnumValueA' | 'EnumValueB')[];
}

export interface WeatherInput {
	forCity: string;
}

export type JSONValue = string | number | boolean | JSONObject | Array<JSONValue>;

export type JSONObject = { [key: string]: JSONValue };

export interface GraphQLError {
	message: string;
	path?: ReadonlyArray<string | number>;
}

export interface InternalCountdownInput {
	from: number;
}

export interface InternalHelloInput {
	hello: string;
}

export interface InternalHelloUserInput {
	name: string;
}

export interface InternalProtectedWeatherInput {
	forCity: string;
}

export interface InternalSetNameInput {
	name: string;
}

export interface InternalTestInput {
	input: ('EnumValueA' | 'EnumValueB')[];
}

export interface InternalWeatherInput {
	forCity: string;
}

export interface InjectedCountdownInput {
	from: number;
}

export interface InjectedHelloInput {
	hello: string;
}

export interface InjectedHelloUserInput {
	name: string;
}

export interface InjectedProtectedWeatherInput {
	forCity: string;
}

export interface InjectedSetNameInput {
	name: string;
}

export interface InjectedTestInput {
	input: ('EnumValueA' | 'EnumValueB')[];
}

export interface InjectedWeatherInput {
	forCity: string;
}

export interface CountdownResponse {
	data?: CountdownResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface FakeWeatherResponse {
	data?: FakeWeatherResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface HelloResponse {
	data?: HelloResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface HelloUserResponse {
	data?: HelloUserResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface PastLaunchesResponse {
	data?: PastLaunchesResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface ProtectedWeatherResponse {
	data?: ProtectedWeatherResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface SetNameResponse {
	data?: SetNameResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface TestResponse {
	data?: TestResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface WeatherResponse {
	data?: WeatherResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface CountdownResponseData {
	countdown: number;
}

export interface FakeWeatherResponseData {
	getCityByName?: {
		id?: string;
		name?: string;
		weather?: {
			summary?: {
				title?: string;
				description?: string;
			};
		};
	};
}

export interface HelloResponseData {
	gql_hello?: string;
}

export interface HelloUserResponseData {
	gql_hello?: string;
}

export interface PastLaunchesResponseData {
	spacex_launchesPast?: {
		mission_name?: string;
		launch_date_local?: string;
		launch_site?: {
			site_name_long?: string;
		};
		links?: {
			article_link?: string;
			video_link?: string;
		};
		rocket?: {
			rocket_name?: string;
			first_stage?: {
				cores?: {
					flight?: number;
				}[];
			};
			second_stage?: {
				payloads?: {
					payload_type?: string;
					payload_mass_kg?: number;
					payload_mass_lbs?: number;
				}[];
			};
		};
	}[];
}

export interface ProtectedWeatherResponseData {
	getCityByName?: {
		name?: string;
		coord?: {
			lat?: number;
			lon?: number;
		};
		weather?: {
			summary?: {
				title?: string;
				description?: string;
				icon?: string;
			};
			temperature?: {
				actual?: number;
				min?: number;
				max?: number;
			};
			wind?: {
				speed?: number;
				deg?: number;
			};
		};
	};
}

export interface SetNameResponseData {
	gql_setName?: string;
}

export interface TestResponseData {
	gql_testField?: {
		enumList: ('EnumValueA' | 'EnumValueB')[];
		stringList?: string[];
	};
}

export interface WeatherResponseData {
	getCityByName?: {
		name?: string;
		coord?: {
			lat?: number;
			lon?: number;
		};
		weather?: {
			summary?: {
				title?: string;
				description?: string;
				icon?: string;
			};
			temperature?: {
				actual?: number;
				min?: number;
				max?: number;
			};
			wind?: {
				speed?: number;
				deg?: number;
			};
		};
	};
}
