name: 'Setup Go'
description: 'This action install go and cache modules and build dependencies'
inputs:
  go-version:
    description: 'The go version to install'
    default: '1.18'
    required: false
  working-directory:
    description: 'The working directory of your go module'
    default: '.'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
