# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: wunderctl
monorepo:
  tag_prefix: 'v'
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ../...
builds:
  - binary: wunderctl
    id: linux
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=ci main.githubAuthDemoClientID={{.Env.GH_AUTH_DEMO_CLIENT_ID}} main.githubAuthDemoClientSecret={{.Env.GH_AUTH_DEMO_CLIENT_SECRET}}
    goos:
      - linux
  - binary: wunderctl
    id: windows
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=ci main.githubAuthDemoClientID={{.Env.GH_AUTH_DEMO_CLIENT_ID}} main.githubAuthDemoClientSecret={{.Env.GH_AUTH_DEMO_CLIENT_SECRET}}
    goos:
      - windows
  - binary: wunderctl
    id: darwin_amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=ci main.githubAuthDemoClientID={{.Env.GH_AUTH_DEMO_CLIENT_ID}} main.githubAuthDemoClientSecret={{.Env.GH_AUTH_DEMO_CLIENT_SECRET}}
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon -log-level=info -log-json .github/goreleaser/gon_amd64.json
  - binary: wunderctl
    id: darwin_arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=ci main.githubAuthDemoClientID={{.Env.GH_AUTH_DEMO_CLIENT_ID}} main.githubAuthDemoClientSecret={{.Env.GH_AUTH_DEMO_CLIENT_SECRET}}
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post: gon .github/goreleaser/gon_arm64.json
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: wundergraph
    name: wundergraph
