version: '3'

services:
  minio:
    build: .
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

volumes:
  data:
