// Code generated by wunderctl. DO NOT EDIT.
package client

type PostInput struct {
	Id float64 `json:"id,omitempty"`
}

type SDLInput struct {
	Sdl string `json:"sdl,omitempty"`
}

type SetFieldInput struct {
	Sdl string `json:"sdl,omitempty"`
}

type UnionInput struct {
	Which string `json:"which,omitempty"`
}

type WeatherInput struct {
	Code string `json:"code,omitempty"`
}

type JSPResponse struct {
	Data   *JSPResponseData `json:"data,omitempty"`
	errors []GraphQLError   `json:"errors"`
}

type JoinResponse struct {
	Data   *JoinResponseData `json:"data,omitempty"`
	errors []GraphQLError    `json:"errors"`
}

type PostResponse struct {
	Data   *PostResponseData `json:"data,omitempty"`
	errors []GraphQLError    `json:"errors"`
}

type PostsResponse struct {
	Data   *PostsResponseData `json:"data,omitempty"`
	errors []GraphQLError     `json:"errors"`
}

type PriceUpdatesResponse struct {
	Data   *PriceUpdatesResponseData `json:"data,omitempty"`
	errors []GraphQLError            `json:"errors"`
}

type SDLResponse struct {
	Data   *SDLResponseData `json:"data,omitempty"`
	errors []GraphQLError   `json:"errors"`
}

type SetFieldResponse struct {
	Data   *SetFieldResponseData `json:"data,omitempty"`
	errors []GraphQLError        `json:"errors"`
}

type UnionResponse struct {
	Data   *UnionResponseData `json:"data,omitempty"`
	errors []GraphQLError     `json:"errors"`
}

type WeatherResponse struct {
	Data   *WeatherResponseData `json:"data,omitempty"`
	errors []GraphQLError       `json:"errors"`
}

type GraphQLError struct {
	Message string
	Path    []interface{}
}

type JSPResponseData struct {
	Jsp_getPosts []*struct {
		Id    float64 `json:"id,omitempty"`
		Title string  `json:"title,omitempty"`
	} `json:"jsp_getPosts,omitempty"`
}

type JoinResponseData struct {
	Posts []*struct {
		Id     float64 `json:"id,omitempty"`
		Title  string  `json:"title,omitempty"`
		UserId float64 `json:"userId,omitempty"`
		User   struct {
			Id       *float64 `json:"id,omitempty"`
			Email    *string  `json:"email,omitempty"`
			Name     *string  `json:"name,omitempty"`
			Username *string  `json:"username,omitempty"`
		} `json:"user,omitempty"`
	} `json:"posts,omitempty"`
}

type PostResponseData struct {
	Post *struct {
		Id     float64 `json:"id,omitempty"`
		Title  string  `json:"title,omitempty"`
		UserId float64 `json:"userId,omitempty"`
		User   struct {
			Id    *float64 `json:"id,omitempty"`
			Email *string  `json:"email,omitempty"`
			Name  *string  `json:"name,omitempty"`
		} `json:"user,omitempty"`
	} `json:"post,omitempty"`
}

type PostsResponseData struct {
	Jsp_getPosts []*struct {
		Id    float64 `json:"id,omitempty"`
		Title string  `json:"title,omitempty"`
	} `json:"jsp_getPosts,omitempty"`
}

type PriceUpdatesResponseData struct {
	Federated_updatedPrice struct {
		Upc   string   `json:"upc,omitempty"`
		Price *float64 `json:"price,omitempty"`
		Name  *string  `json:"name,omitempty"`
	} `json:"federated_updatedPrice,omitempty"`
}

type SDLResponseData struct {
	Sdl_setSdlField string `json:"sdl_setSdlField,omitempty"`
}

type SetFieldResponseData struct {
	Sdl_setSdlField string `json:"sdl_setSdlField,omitempty"`
}

type UnionResponseData struct {
	Public_gqlUnion *struct {
		__typename *string `json:"__typename,omitempty"`
		Id         *string `json:"id,omitempty"`
		Name       *string `json:"name,omitempty"`
	} `json:"public_gqlUnion,omitempty"`
}

type WeatherResponseData struct {
	Country *struct {
		Code    string  `json:"code,omitempty"`
		Name    string  `json:"name,omitempty"`
		Capital *string `json:"capital,omitempty"`
		Weather struct {
			Summary *struct {
				Title       *string `json:"title,omitempty"`
				Description *string `json:"description,omitempty"`
			} `json:"summary,omitempty"`
			Temperature *struct {
				Actual    *float64 `json:"actual,omitempty"`
				FeelsLike *float64 `json:"feelsLike,omitempty"`
			} `json:"temperature,omitempty"`
		} `json:"weather,omitempty"`
	} `json:"country,omitempty"`
}
