// Code generated by wunderctl. DO NOT EDIT.

export interface MissionsInput {
	find?: spacex_MissionsFind;
}

export interface spacex_MissionsFind {
	id?: string;
	manufacturer?: string;
	name?: string;
	payload_id?: string;
}

export type JSONValue = string | number | boolean | JSONObject | Array<JSONValue>;

export type JSONObject = { [key: string]: JSONValue };

export interface GraphQLError {
	message: string;
	path?: ReadonlyArray<string | number>;
}

export interface InternalMissionsInput {
	find?: spacex_MissionsFind;
}

export interface InjectedMissionsInput {
	find?: spacex_MissionsFind;
}

export interface DragonsResponse {
	data?: DragonsResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface MissionsResponse {
	data?: MissionsResponseData;
	errors?: ReadonlyArray<GraphQLError>;
}

export interface DragonsResponseData {
	spacex_dragons?: {
		name?: string;
		active?: boolean;
	}[];
}

export interface MissionsResponseData {
	spacex_missions?: {
		id?: string;
		name?: string;
		manufacturers?: string[];
	}[];
}
