name: publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @wundergraph/wunderctl@latest
      - run: npm install
        working-directory: '.wundergraph'
      - run: npm run deploy
        working-directory: '.wundergraph'
        env:
          WUNDERGRAPH_TOKEN: ${{ secrets.WUNDERGRAPH_TOKEN }}
