name: Engine CI
on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**/*.go'
      - 'types/**/*'
      - 'go.mod'
      - 'go.sum'
      - '.github/actions/go/action.yaml'
      - '.github/actions/node/action.yaml'
      - '.github/workflows/engine-ci.yaml'
  pull_request:
    branches:
      - main
      - next
    paths-ignore:
      - '**/*.go'
      - 'types/**/*'
      - 'go.mod'
      - 'go.sum'
      - '.github/actions/go/action.yaml'
      - '.github/actions/node/action.yaml'
      - '.github/workflows/engine-ci.yaml'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
