name: NPM Packages CI
on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - 'packages/**/*'
      - 'testapps/**/*'
      - '.github/actions/go/action.yaml'
      - '.github/actions/node/action.yaml'
      - '.github/workflows/packages-ci.yaml'
      - 'examples/**/*'
  pull_request:
    branches:
      - main
      - next
    paths-ignore:
      - 'testapps/**/*'
      - 'packages/**/*'
      - '.github/actions/go/action.yaml'
      - '.github/actions/node/action.yaml'
      - '.github/workflows/packages-ci.yaml'
      - 'examples/**/*'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
