name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Check if PR title follows conventional commit guidelines
        run: |
          npm i -g @commitlint/cli @commitlint/config-conventional
          echo "${{ github.event.pull_request.title }}" | commitlint
