name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR title follows conventional commit guidelines
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
